language: dart
dart: ["stable", "dev"]
with_content_shell: true
sudo: false

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  #- pub run test -p content-shell 
  - set -e
  - dartanalyzer --fatal-hints --fatal-warnings lib/stagexl_spine.dart
