name: stagexl_spine
version: 0.2.0
author: Bernhard Pichler <support@stagexl.org>
description: The Spine runtime for the StageXL library.
homepage: http://www.stagexl.org
environment:
  sdk: '>=0.1.6 <2.0.0'
dependencies:
  browser: any
  stagexl: '>=0.10.0 <0.11.0'
transformers:
- $dart2js:
    commandLineOptions: ["--trust-type-annotations"]
    minify: true
  