name: stagexl_spine
version: 0.10.0+1
author: Bernhard Pichler <support@stagexl.org>
description: The Spine runtime for the StageXL library.
homepage: https://github.com/bp74/StageXL_Spine

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  stagexl: '>=1.4.0 <2.0.0'

dev_dependencies:
  build_test: any
  build_runner: any
  build_web_compilers: any
