name: stagexl_spine
version: 0.8.4
author: Bernhard Pichler <support@stagexl.org>
description: The Spine runtime for the StageXL library.
homepage: https://github.com/bp74/StageXL_Spine

environment:
  sdk: '>=1.20.0 <2.0.0'

dependencies:
  browser: any
  stagexl: '^1.0.0'

transformers:
- $dart2js:
    commandLineOptions: ["--trust-type-annotations", "--trust-primitives"]
    minify: true
