name: stagexl_spine
version: 0.6.0
author: Bernhard Pichler <support@stagexl.org>
description: The Spine runtime for the StageXL library.
homepage: https://github.com/bp74/StageXL_Spine
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  browser: any
  stagexl: '>=0.13.0 <0.14.0'
transformers:
- $dart2js:
    commandLineOptions: ["--trust-type-annotations", "--trust-primitives"]
    minify: true
